{% set name = "libcint" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sunqm/libcint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6512b20aed1538e1f73bf97e6cfbfefb891598731c8e95640b6bf2e825065b0a

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make

test:
  commands:
    - cd testsuite
    - python test_cint.py --quick
    - python test_3c2e.py --quick
  requires:
    - numpy
    - python
  source_files:
    - testsuite

about:
  home: https://github.com/sunqm/libcint
  summary: general GTO integrals for quantum chemistry
  dev_url: https://github.com/sunqm/libcint
  doc_url: http://wiki.sunqm.net/libcint
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
