schema_version: 1

context:
  name: libcint
  version: 6.1.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/sunqm/libcint/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e4d977d4aeb4d5b87639ea57a2d2f1d5c1001f3f94e480b08c297a6cbc186f27
  patches:
    - 0001-Fix-test-location.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake
    - make
  run_exports:
    - ${{ pin_subpackage(name, lower_bound='x.x', upper_bound='x.x') }}

tests:
  - files:
      source:
        - testsuite
    requirements:
      run:
        - numpy
        - python
    script:
      - cd testsuite
      - python test_cint.py --quick
      - python test_3c2e.py --quick

about:
  summary: general GTO integrals for quantum chemistry
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/sunqm/libcint
  repository: https://github.com/sunqm/libcint
  documentation: http://wiki.sunqm.net/libcint

extra:
  recipe-maintainers:
    - BastianZim
    - chillenb
